[package]
name = "gclone"
version = "0.1.0"
edition = "2024"

[[bin]]
edition = "2024"
name = "gclone"
path = "src/main.rs"

[dependencies]
dirs = "6.0.0"
toml = "0.8.20"
serde = { version = "1", features = ["derive"] }
