[package]
name = "gclone"
version = "0.1.0"
edition = "2021"

[[bin]]
edition = "2021"
name = "gclone"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
